apiVersion: v1
kind: Service
metadata:
  name: v3maindrupal-service
 # namespace: v3md-drupal
spec:
  selector:
    app: drupal
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
      nodePort: 30004
      
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: v3md-drupal-pvc
  # namespace: v3md-drupal
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v3maindrupal-deployment
  # namespace: v3md-drupal
  labels:
     app: drupal
     type: front-end
spec:
  template:
     metadata:
       name: drupal-pod
       labels: 
         app: drupal
         type: front-end
     spec:
         containers:
           - name: drupal
             image: "docker.io/v3mainproducts/drupal"
             imagePullPolicy: Always
             volumeMounts:
             - name: vol-drupal
               mountPath: /var/www/html
         imagePullSecrets:
         - name: drupalsecret
         volumes: 
          - name: vol-drupal
            persistentVolumeClaim: 
              claimName: v3md-drupal-pvc
  replicas: 1
  selector:
    matchLabels:
      type: front-end
