apiVersion: apps/v1
kind: Deployment
metadata:
  name: v3maindrupal-deployment
  labels:
     app: drupal
     type: front-end
spec:
  template:
     metadata:
       name: drupal-pod
       labels: 
         app: drupal
         type: front-end
     spec:
         containers:
           - name: drupal
             image: "docker.io/v3mainproducts/drupal"
             imagePullPolicy: Always
         imagePullSecrets:
         - name: drupalsecret
  replicas: 1
  selector:
    matchLabels:
      type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: v3maindrupal-service
spec:
  selector:
    app: drupal
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
      nodePort: 30000
