kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: drupalpoc
spec:
  rules:
  - host: drupalpoc.v3main.com
    http:
      paths:
       - backend:
            serviceName: drupalpoc-service
            servicePort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: drupalpoc-service
spec:
  selector:
    app: drupalpoc
  ports:
    - name: app-port
      port: 80
      targetPort: 8080

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: drupalpoc
spec:
  template:
     metadata:
       labels: 
         app: drupalpoc
     spec:
         containers:
           - name: drupalpoc
             image: "v3mainproducts/drupal:latest"
             env:
             - name: env
               value: "dev"
             imagePullPolicy: Always
             ports:
             - containerPort: 8080
               protocols: TCP
  replicas: 1
  selector:
    matchLabels:
      app: drupalpoc