apiVersion: v1
kind: Service
metadata:
  name: v3mainmysql-service
  namespace: v3md-drupal
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 3306
      port: 3306

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: v3md-mysql-pvc
  namespace: v3md-drupal
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v3mainmysql-deployment
  namespace: v3md-drupal
  labels:
     app: mysql
     type: back-end
spec:
  template:
     metadata:
       name: mysql-pod
       labels: 
         app: mysql
         type: back-end
     spec:
         containers:
           - name: mysql
             image: "docker.io/mysql:5.7.28"
             volumeMounts: 
             - mountPath: /var/lib/mysql
               name: vol-drupal
               subPath: dbdata
             env:
             - name: MYSQL_ROOT_PASSWORD
               value: "password"
             - name: MYSQL_PASSWORD
               value: "password"
             - name: MYSQL_DATABASE
               value: "drupal"
             - name: MYSQL_USER
               value: "user"
             imagePullPolicy: Always
         imagePullSecrets:
         - name: drupalsecret
         volumes: 
         - name: vol-drupal
           persistentVolumeClaim: 
              claimName: v3md-mysql-pvc
  replicas: 1
  selector:
    matchLabels:
      type: back-end
